#page title
page_title                                :                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1603024803                        # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                   # Enter Google Play Store URL.
presskit_download_link                    :                                   # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : For iPhone, iPad, and Mac.        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Block distracting Apps & Websites on iPhone, iPad, and Mac.

enable_smart_app_banner                   : true                              # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Michael Tigas                                
your_link                                 : https://twitter.com/michael_tigas
your_city                                 : Melbourne, Australia. 🇦🇺 🦘
email_address                             : ochi@michaeltigas.com.au
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : OchiTheApp
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Flexible Focus Sessions
    description                           : Create repeatable sessions for different tasks, structured with Focused Work, Break and Planning stages.
    fontawesome_icon_name                 : stopwatch
    
  - title                                 : Self-Accountability
    description                           : Each session encourages you to focus on a specific task or goal, which remains on-screen during a session.
    fontawesome_icon_name                 : sticky-note

  - title                                 : Focus Reminders
    description                           : Avoid distractions during a focus session, with fun periodic reminders to maintain your focus.
    fontawesome_icon_name                 : exclamation

  - title                                 : Session Reflection
    description                           : Rate your level of productivity during the session. Journal about what worked well for you and what didn't.
    fontawesome_icon_name                 : pen

  - title                                 : Daily Goals & Streaks
    description                           : Create healthy productivity habits by completing focus session, focused work, and break goals each day.
    fontawesome_icon_name                 : chart-pie

  - title                                 : Time Tracking with Toggl
    description                           : Assign Projects, Tags, and Tasks to each session for a complete breakdown on time spent.
    fontawesome_icon_name                 : power-off


platform_features                         :

  - title                                 : Siri Shortcuts
    description                           : Start a Focus Session with Siri. Pause, Skip, Restart the current stage, and adjust the timer volume.
    fontawesome_icon_name                 : layer-group

  - title                                 : Shortcut Automations
    description                           : Automatically turn a Focus on or off. Manage distractions and trigger shortcuts mid-session.
    fontawesome_icon_name                 : eye

  - title                                 : Block Apps & Websites
    description                           : Automatically block iOS/Mac apps & websites until you've completed your focus session.
    fontawesome_icon_name                 : ban

  - title                                 : Mid-session alerts on all devices
    description                           : Start a focus session on Mac and receive updates on iPhone, iPad, Apple Watch, and vice versa.
    fontawesome_icon_name                 : bell

  - title                                 : iCloud Syncing
    description                           : Work from your iPhone, iPad, or Mac. Created sessions and productivity stats are synced between each device.
    fontawesome_icon_name                 : sync

  - title                                 : Share Extensions
    description                           : Select a task in your favourite task manager app, and quickly start a focus session via the Share Sheet.
    fontawesome_icon_name                 : external-link-alt

  - title                                 : Themeable Widgets
    description                           : Add Current Session, Daily Goals, and Session Select widgets, with Pure Black & Completely Black themes.
    fontawesome_icon_name                 : th-large

  - title                                 : App Icons
    description                           : Pick an app icon that matches your homescreen. Coloured, Light, and Dark variants.
    fontawesome_icon_name                 : images

  - title                                 : Productivity Export
    description                           : Export completed sessions & breadcrumbs in CSV format, and analyse them in Numbers.
    fontawesome_icon_name                 : file-download

  - title                                 : Privacy Focused
    description                           : No account signups. All user data is securely stored and managed via iCloud, with each session run on-device.
    fontawesome_icon_name                 : mask

  - title                                 : More iOS & iPadOS Goodies
    description                           : VoiceOver, Split View & Slide Over, Dark Mode themes, Drag & Drop, Quick Actions, Low Power Mode.
    fontawesome_icon_name                 : mobile-alt

  - title                                 : More macOS Goodies
    description                           : Keyboard Shortcuts, Menu Bar Timer, Shortcuts for Mac, Alfred automation, URL Schemes.
    fontawesome_icon_name                 : laptop




# Press Review List                       Edit, add or remove press reviews to be presented.
pressreviews                              :

  - author                                : Ryan Christoffel
    quote                                 : A simple, but valuable utility for creating timed focus sessions of productivity.
    sitename                              : MacStories
    siteurl                               : https://www.macstories.net/reviews/focused-work-review-staying-on-task-amidst-growing-distractions/
    fontawesome_icon_name                 : heart
    
  - author                                : Victor Marks
    quote                                 : Focused Work is a tool that helps overcome that first step.
    sitename                              : Knapsack
    siteurl                               : https://knapsack.news/focused-work-how-do-we-get-anything-done-at-all/
    fontawesome_icon_name                 : heart
    
  - author                                : Oliver Haslam
    quote                                 : Focused Work helps you stay on track better than ever.
    sitename                              : iMore
    siteurl                               : https://www.imore.com/focused-work-gains-ios-14-home-screen-widgets-help-you-stay-track-better-ever/
    fontawesome_icon_name                 : heart



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/ochi_coverimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#4c69af"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#606BC5"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#606BC5"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown