#page title
page_title                                :                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1603024803                        # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://newsletter.ochithe.app/join                                  # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                   # Enter Google Play Store URL.
presskit_download_link                    :                                   # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : For iPhone, iPad, and Mac.        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Block distracting Apps & Websites on iPhone, iPad, and Mac.

enable_smart_app_banner                   : true                              # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Michael Tigas                                
your_link                                 : https://twitter.com/michael_tigas
your_city                                 : Melbourne, Australia. 🇦🇺 🦘
email_address                             : ochi@michaeltigas.com.au
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : OchiTheApp
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Configurable Filters
    description                           : Create and start Timed Filters that are configured to Block or Allow access.
    fontawesome_icon_name                 : stopwatch
    
  - title                                 : Block Apps
    description                           : Prevent access to iOS and macOS apps while a filter is active.
    fontawesome_icon_name                 : stopwatch
    
  - title                                 : Block Websites & Categories
    description                           : Prevent access to websites, including selectable categories such as Chat, News, and Social Media.
    fontawesome_icon_name                 : sticky-note

  - title                                 : Automations
    description                           : Assign shortcuts to filters that can automatically turn a Focus on or off.
    fontawesome_icon_name                 : exclamation

  - title                                 : Suspend Filtering
    description                           : Set a limit on how frequently a timed filter can be suspended, per hour.
    fontawesome_icon_name                 : pen

  - title                                 : Filter Privacy
    description                           : Obfuscate and prevent editing filter details with Biometric or Apple Watch unlock.
    fontawesome_icon_name                 : chart-pie

  # - title                                 : Time Tracking with Toggl
  #   description                           : Assign Projects, Tags, and Tasks to each session for a complete breakdown on time spent.
  #   fontawesome_icon_name                 : power-off


platform_features                         :

  - title                                 : Siri Shortcuts
    description                           : Turn a Filter on with Siri. Suspend a filter if you need temporary access to an app or website.
    fontawesome_icon_name                 : layer-group

  - title                                 : Shortcut Automations
    description                           : Automatically turn a Focus on or off. Manage distractions and trigger shortcuts when a filter starts & ends.
    fontawesome_icon_name                 : eye

  # - title                                 : Block Apps & Websites
  #   description                           : Automatically block iOS/Mac apps & websites until you've completed your focus session.
  #   fontawesome_icon_name                 : ban

  # - title                                 : Mid-session alerts on all devices
  #   description                           : Start a focus session on Mac and receive updates on iPhone, iPad, Apple Watch, and vice versa.
  #   fontawesome_icon_name                 : bell

  - title                                 : iCloud Syncing
    description                           : Created filters and filter statistics are synced between iPhone, iPad, and Mac.
    fontawesome_icon_name                 : sync

  # - title                                 : Share Extensions
  #   description                           : Select a task in your favourite task manager app, and quickly start a focus session via the Share Sheet.
  #   fontawesome_icon_name                 : external-link-alt

  - title                                 : Themeable Widgets
    description                           : Add a Current Filter widget, with adjustable themes.
    fontawesome_icon_name                 : th-large

  - title                                 : App Icons
    description                           : Pick an app icon that matches your homescreen. Coloured, Light, and Dark variants.
    fontawesome_icon_name                 : images

  # - title                                 : Productivity Export
  #   description                           : Export completed sessions & breadcrumbs in CSV format, and analyse them in Numbers.
  #   fontawesome_icon_name                 : file-download

  - title                                 : Privacy Focused
    description                           : No account signups. All user data is securely stored and managed via iCloud, with each session run on-device.
    fontawesome_icon_name                 : mask

  # - title                                 : More iOS & iPadOS Goodies
  #   description                           : VoiceOver, Split View & Slide Over, Dark Mode themes, Drag & Drop, Quick Actions, Low Power Mode.
  #   fontawesome_icon_name                 : mobile-alt

  # - title                                 : More macOS Goodies
  #   description                           : Keyboard Shortcuts, Menu Bar Timer, Shortcuts for Mac, Alfred automation, URL Schemes.
  #   fontawesome_icon_name                 : laptop




# Press Review List                       Edit, add or remove press reviews to be presented.
pressreviews                              :

  - author                                : 
    quote                                 : 
    sitename                              : 
    siteurl                               : 
    fontawesome_icon_name                 : heart
    
  - author                                : 
    quote                                 : 
    sitename                              : 
    siteurl                               : 
    fontawesome_icon_name                 : heart
    
  - author                                : 
    quote                                 : 
    sitename                              : 
    siteurl                               : 
    fontawesome_icon_name                 : heart



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/ochi_coverimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#4c69af"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#606BC5"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#606BC5"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown