#page title
page_title                                :                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1603024803                        # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/apple-store/id1603024803?pt=118633132&ct=website_cta&mt=8 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                   # Enter Google Play Store URL.
presskit_download_link                    : https://impresskit.net/ochi                                  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : For iPhone, iPad, and Mac.        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Block distracting Apps & Websites on iPhone, iPad, and Mac.

enable_smart_app_banner                   : true                              # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Michael Tigas
your_link                                 : https://tigas.io
your_city                                 : Melbourne, Australia. 🇦🇺 🦘
email_address                             : ochi@michaeltigas.com.au
facebook_username                         :
instagram_username                        :
twitter_username                          : OchiTheApp
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Control access to Apps & Websites
    description                           : Apply Block or Allow filters for groups of iOS apps, Mac apps, and websites.
    fontawesome_icon_name                 : mobile-alt

  - title                                 : Filter Website Categories
    description                           : Prevent access to groups of websites, including Social Media, Chat, and News.
    fontawesome_icon_name                 : globe

  - title                                 : Schedule Recurring Filters
    description                           : No more late night Twitter, Facebook, or YouTube on weeknights!
    fontawesome_icon_name                 : calendar-check

  - title                                 : Apply Multiple Filters
    description                           : Simultaneously run Timed and Untimed filters configured with different rules.
    fontawesome_icon_name                 : stopwatch

  - title                                 : Suspend Filtering
    description                           : Limit how often filters can be temporarily suspended.
    fontawesome_icon_name                 : pause

  - title                                 : Filter Automations (Mac)
    description                           : Assign shortcuts to filters that turn on Focus and filters on other devices.
    fontawesome_icon_name                 : eye

  - title                                 : Lock & Hide Filter Details
    description                           : Keep filter details private, and prevent editing with Biometric authentication.
    fontawesome_icon_name                 : lock

  - title                                 : Dashboard Stats
    description                           : Observe how many distracting apps & websites you've avoided each day.
    fontawesome_icon_name                 : chart-area

  # - title                                 : Time Tracking with Toggl
  #   description                           : Assign Projects, Tags, and Tasks to each session for a complete breakdown on time spent.
  #   fontawesome_icon_name                 : power-off


platform_features                         :

  - title                                 : Siri Shortcuts
    description                           : Integrate Ochi into your workflow with Shortcuts. Control filtering with Siri.
    fontawesome_icon_name                 : layer-group

  # - title                                 : Shortcut Automations
  #   description                           : Automatically turn a Focus on or off. Manage distractions and trigger shortcuts when a filter starts & ends.
  #   fontawesome_icon_name                 : eye

  # - title                                 : Block Apps & Websites
  #   description                           : Automatically block iOS/Mac apps & websites until you've completed your focus session.
  #   fontawesome_icon_name                 : ban

  # - title                                 : Mid-session alerts on all devices
  #   description                           : Start a focus session on Mac and receive updates on iPhone, iPad, Apple Watch, and vice versa.
  #   fontawesome_icon_name                 : bell

  - title                                 : iCloud Syncing
    description                           : All filters and filtering statistics are synced between iPhone, iPad, and Mac.
    fontawesome_icon_name                 : sync

  # - title                                 : Share Extensions
  #   description                           : Select a task in your favourite task manager app, and quickly start a focus session via the Share Sheet.
  #   fontawesome_icon_name                 : external-link-alt

  - title                                 : Customizable Widgets
    description                           : Start filters from your Home Screen, Control Center, and Lock Screen.
    fontawesome_icon_name                 : th-large

  - title                                 : App Icons
    description                           : Icons that match your wallpaper. Light, Dark, and colored variants.
    fontawesome_icon_name                 : images

  # - title                                 : Productivity Export
  #   description                           : Export completed sessions & breadcrumbs in CSV format, and analyse them in Numbers.
  #   fontawesome_icon_name                 : file-download

  - title                                 : Privacy Focused
    description                           : All user data is securely stored and managed via iCloud, with filters exclusively run on-device.
    fontawesome_icon_name                 : mask

  - title                                 : More Goodies
    description                           : Split View, Slide Over, Keyboard Shortcuts, Menu Bar app, Shortcuts for Mac, and more.
    fontawesome_icon_name                 : mobile-alt

  # - title                                 : More iOS & iPadOS Goodies
  #   description                           : VoiceOver, Split View & Slide Over, Dark Mode themes, Drag & Drop, Quick Actions, Low Power Mode.
  #   fontawesome_icon_name                 : mobile-alt

  # - title                                 : More macOS Goodies
  #   description                           : Keyboard Shortcuts, Menu Bar Timer, Shortcuts for Mac, Alfred automation, URL Schemes.
  #   fontawesome_icon_name                 : laptop




# Press Review List                       Edit, add or remove press reviews to be presented.
pressreviews                              :

  # - author                                :
  #   quote                                 :
  #   sitename                              :
  #   siteurl                               :
  #   fontawesome_icon_name                 : heart

  # - author                                :
  #   quote                                 :
  #   sitename                              :
  #   siteurl                               :
  #   fontawesome_icon_name                 : heart

  # - author                                :
  #   quote                                 :
  #   sitename                              :
  #   siteurl                               :
  #   fontawesome_icon_name                 : heart



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/ochi_coverimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#77A2F6"
cover_overlay_transparency                : 0.2

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#77a2f6"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#77a2f6"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#000000"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown